spring:
  application:
    name: gateway-server
  config:
    import: 'optional:configserver:http://config-server:3100'
  cloud:
    config:
      uri: http://config-server:3100  # 추가
      fail-fast: false
      discovery:
        enabled: true
        service-id: config-server

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:localhost}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:3150/eureka/}

server:
  port: 3000

